const ALL_PERMISSIONS = {
  'notice.view': 'নোটিশ দেখা',
  'notice.create': 'নোটিশ তৈরি করা',
  'notice.edit': 'নোটিশ সম্পাদনা',
  'notice.delete': 'নোটিশ মুছে ফেলা',
  'notice.pin': 'নোটিশ pin করা',
  'notice.publish': 'নোটিশ publish করা',
  'notice.archive': 'নোটিশ archive করা',

  'meeting.view': 'মিটিং দেখা',
  'meeting.create': 'মিটিং তৈরি করা',
  'meeting.edit': 'মিটিং সম্পাদনা',
  'meeting.delete': 'মিটিং মুছে ফেলা',
  'meeting.attendance': 'উপস্থিতি নেওয়া',
  'meeting.minutes': 'কার্যবিবরণী লেখা',

  'tour.view': 'ট্যুর দেখা',
  'tour.create': 'ট্যুর তৈরি করা',
  'tour.edit': 'ট্যুর সম্পাদনা',
  'tour.delete': 'ট্যুর মুছে ফেলা',
  'tour.manage_registration': 'ট্যুর নিবন্ধন পরিচালনা',

  'blog.view': 'ব্লগ দেখা',
  'blog.approve': 'ব্লগ অনুমোদন',
  'blog.reject': 'ব্লগ বাতিল',
  'blog.delete': 'ব্লগ মুছে ফেলা',
  'blog.edit_any': 'যেকোনো ব্লগ সম্পাদনা',

  'gallery.view': 'গ্যালারি দেখা',
  'gallery.upload': 'ছবি আপলোড করা',
  'gallery.approve': 'ছবি অনুমোদন',
  'gallery.delete': 'ছবি মুছে ফেলা',
  'gallery.manage_albums': 'অ্যালবাম পরিচালনা',

  'member.view': 'সদস্য তালিকা দেখা',
  'member.approve': 'সদস্য অনুমোদন',
  'member.reject': 'সদস্য বাতিল',
  'member.suspend': 'সদস্য suspend করা',
  'member.edit': 'সদস্য তথ্য সম্পাদনা',
  'member.reset_password': 'পাসওয়ার্ড রিসেট',
  'member.export': 'সদস্য তালিকা export',

  'finance.view': 'আর্থিক তথ্য দেখা',
  'finance.approve_fees': 'ফি অনুমোদন',
  'finance.add_expense': 'ব্যয় যোগ করা',
  'finance.add_donation': 'দান যোগ করা',
  'finance.waive_fee': 'ফি মওকুফ করা',
  'finance.export': 'আর্থিক প্রতিবেদন export',

  'notification.send': 'বিজ্ঞপ্তি পাঠানো',
  'notification.view_log': 'বিজ্ঞপ্তি লগ দেখা',

  'poll.create': 'পোল তৈরি করা',
  'poll.edit': 'পোল সম্পাদনা',
  'poll.delete': 'পোল মুছে ফেলা',
  'poll.view_results': 'পোল ফলাফল দেখা',

  'homepage.committee': 'কমিটি পরিচালনা',
  'homepage.achievements': 'অর্জন পরিচালনা',
  'homepage.testimonials': 'প্রশংসাপত্র পরিচালনা',
  'homepage.partners': 'সহযোগী পরিচালনা',

  'settings.org': 'সংগঠন সেটিংস',
  'settings.appearance': 'চেহারা সেটিংস',
  'settings.security': 'নিরাপত্তা সেটিংস',
  'settings.roles': 'ভূমিকা ব্যবস্থাপনা',
  'settings.backup': 'ব্যাকআপ',

  'audit.view': 'অডিট লগ দেখা',
}

const PERMISSION_GROUPS = [
  ['notice', 'নোটিশ ব্যবস্থাপনা'],
  ['meeting', 'মিটিং ব্যবস্থাপনা'],
  ['tour', 'ট্যুর ব্যবস্থাপনা'],
  ['blog', 'ব্লগ ব্যবস্থাপনা'],
  ['gallery', 'গ্যালারি ব্যবস্থাপনা'],
  ['member', 'সদস্য ব্যবস্থাপনা'],
  ['finance', 'আর্থিক ব্যবস্থাপনা'],
  ['notification', 'বিজ্ঞপ্তি'],
  ['poll', 'পোল'],
  ['homepage', 'হোমপেজ কনটেন্ট'],
  ['settings', 'সেটিংস'],
  ['audit', 'অডিট'],
]

const SETTINGS_PERMISSIONS = Object.keys(ALL_PERMISSIONS).filter((permission) =>
  permission.startsWith('settings.'),
)

const DEFAULT_ROLES = [
  {
    color: '#111827',
    description: 'সকল অনুমতি সহ প্রধান অ্যাডমিন',
    isDefault: true,
    isSystem: true,
    name: 'admin',
    nameEnglish: 'Admin',
    permissions: ['*'],
  },
  {
    color: '#00ADB5',
    description: 'সাধারণ অনুমোদিত সদস্য',
    isDefault: true,
    isSystem: true,
    name: 'member',
    nameEnglish: 'Member',
    permissions: [
      'notice.view',
      'meeting.view',
      'tour.view',
      'blog.view',
      'gallery.view',
      'gallery.upload',
      'poll.view_results',
    ],
  },
  {
    color: '#8B5CF6',
    description: 'ব্লগ ও গ্যালারি moderation দায়িত্বে',
    isDefault: true,
    isSystem: true,
    name: 'moderator',
    nameEnglish: 'Moderator',
    permissions: [
      'blog.view',
      'blog.approve',
      'blog.reject',
      'gallery.view',
      'gallery.upload',
      'gallery.approve',
      'poll.view_results',
    ],
  },
  {
    color: '#6366F1',
    description: 'নোটিশ তৈরি ও পরিচালনার দায়িত্বে',
    name: 'notice_manager',
    nameEnglish: 'Notice Manager',
    permissions: [
      'notice.view',
      'notice.create',
      'notice.edit',
      'notice.publish',
      'notice.pin',
      'notice.archive',
    ],
  },
  {
    color: '#0F6E56',
    description: 'সকল কন্টেন্ট পরিচালনার দায়িত্বে',
    name: 'content_manager',
    nameEnglish: 'Content Manager',
    permissions: [
      'notice.view',
      'notice.create',
      'notice.edit',
      'notice.publish',
      'notice.pin',
      'notice.archive',
      'notice.delete',
      'blog.view',
      'blog.approve',
      'blog.reject',
      'blog.delete',
      'gallery.view',
      'gallery.upload',
      'gallery.approve',
      'gallery.delete',
      'gallery.manage_albums',
      'meeting.view',
      'tour.view',
      'homepage.committee',
      'homepage.achievements',
      'homepage.testimonials',
      'homepage.partners',
    ],
  },
  {
    color: '#854F0B',
    description: 'আর্থিক লেনদেন পরিচালনার দায়িত্বে',
    name: 'finance_manager',
    nameEnglish: 'Finance Manager',
    permissions: [
      'finance.view',
      'finance.approve_fees',
      'finance.add_expense',
      'finance.add_donation',
      'finance.export',
      'member.view',
      'notification.send',
    ],
  },
  {
    color: '#993C1D',
    description: 'মিটিং ও ট্যুর পরিচালনার দায়িত্বে',
    name: 'event_manager',
    nameEnglish: 'Event Manager',
    permissions: [
      'meeting.view',
      'meeting.create',
      'meeting.edit',
      'meeting.attendance',
      'meeting.minutes',
      'tour.view',
      'tour.create',
      'tour.edit',
      'tour.manage_registration',
      'gallery.manage_albums',
      'gallery.upload',
      'poll.create',
      'poll.edit',
      'poll.view_results',
      'notification.send',
    ],
  },
  {
    color: '#185FA5',
    description: 'সদস্য নিবন্ধন ও তথ্য পরিচালনার দায়িত্বে',
    name: 'member_manager',
    nameEnglish: 'Member Manager',
    permissions: [
      'member.view',
      'member.approve',
      'member.reject',
      'member.edit',
      'member.reset_password',
      'member.export',
      'notification.send',
    ],
  },
]

module.exports = {
  ALL_PERMISSIONS,
  DEFAULT_ROLES,
  PERMISSION_GROUPS,
  SETTINGS_PERMISSIONS,
}
