const express = require('express')
const activityRoutes = require('./activityRoutes')
const authRoutes = require('./authRoutes')
const donationRoutes = require('./donationRoutes')
const expenseRoutes = require('./expenseRoutes')
const healthRoutes = require('./healthRoutes')
const meetingRoutes = require('./meetingRoutes')
const memberRoutes = require('./memberRoutes')
const noticeRoutes = require('./noticeRoutes')
const paymentRoutes = require('./paymentRoutes')
const registrationRoutes = require('./registrationRoutes')
const ruleRoutes = require('./ruleRoutes')
const settingsRoutes = require('./settingsRoutes')
const tourRoutes = require('./tourRoutes')

const router = express.Router()

router.use('/activities', activityRoutes)
router.use('/auth', authRoutes)
router.use('/donations', donationRoutes)
router.use('/expenses', expenseRoutes)
router.use('/health', healthRoutes)
router.use('/meetings', meetingRoutes)
router.use('/members', memberRoutes)
router.use('/notices', noticeRoutes)
router.use('/payments', paymentRoutes)
router.use('/registrations', registrationRoutes)
router.use('/rules', ruleRoutes)
router.use('/settings', settingsRoutes)
router.use('/tours', tourRoutes)

module.exports = router
