const express = require('express')
const activityRoutes = require('./activityRoutes')
const achievementRoutes = require('./achievementRoutes')
const adminControlRoutes = require('./adminControlRoutes')
const auditRoutes = require('./auditRoutes')
const authRoutes = require('./authRoutes')
const blogRoutes = require('./blogRoutes')
const backupRoutes = require('./backupRoutes')
const committeeRoutes = require('./committeeRoutes')
const donationRoutes = require('./donationRoutes')
const expenseRoutes = require('./expenseRoutes')
const feeRoutes = require('./feeRoutes')
const financeRoutes = require('./financeRoutes')
const galleryRoutes = require('./galleryRoutes')
const healthRoutes = require('./healthRoutes')
const meetingRoutes = require('./meetingRoutes')
const memberRoutes = require('./memberRoutes')
const notificationRoutes = require('./notificationRoutes')
const noticeRoutes = require('./noticeRoutes')
const paymentRoutes = require('./paymentRoutes')
const partnerRoutes = require('./partnerRoutes')
const pollRoutes = require('./pollRoutes')
const receiptRoutes = require('./receiptRoutes')
const registrationRoutes = require('./registrationRoutes')
const ruleRoutes = require('./ruleRoutes')
const settingsRoutes = require('./settingsRoutes')
const testimonialRoutes = require('./testimonialRoutes')
const tourRoutes = require('./tourRoutes')
const uploadRoutes = require('./uploadRoutes')

const router = express.Router()

router.use('/activities', activityRoutes)
router.use('/achievements', achievementRoutes)
router.use('/admin-controls', adminControlRoutes)
router.use('/audit-logs', auditRoutes)
router.use('/auth', authRoutes)
router.use('/blogs', blogRoutes)
router.use('/backup', backupRoutes)
router.use('/committee', committeeRoutes)
router.use('/donations', donationRoutes)
router.use('/expenses', expenseRoutes)
router.use('/fees', feeRoutes)
router.use('/finance', financeRoutes)
router.use('/gallery', galleryRoutes)
router.use('/health', healthRoutes)
router.use('/meetings', meetingRoutes)
router.use('/members', memberRoutes)
router.use('/notifications', notificationRoutes)
router.use('/notices', noticeRoutes)
router.use('/payments', paymentRoutes)
router.use('/partners', partnerRoutes)
router.use('/polls', pollRoutes)
router.use('/receipts', receiptRoutes)
router.use('/registrations', registrationRoutes)
router.use('/rules', ruleRoutes)
router.use('/settings', settingsRoutes)
router.use('/testimonials', testimonialRoutes)
router.use('/tours', tourRoutes)
router.use('/uploads', uploadRoutes)

module.exports = router
